openapi: 3.1.0
info:
  title: Customer Service API
  description: Provides customer data and operations.
  version: v1
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /customers:
    get:
      tags:
      - customer-controller
      summary: Returns all customers
      description: Provides a list of all customers stored in the system
      operationId: getCustomers
      responses:
        "200":
          description: List was successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CustomerDto"
              examples:
                Example customer list:
                  description: Example customer list
                  value:
                  - id: 1
                    firstName: string
                    lastName: string
                    birthDate: 2025-04-05
                    email: string
        "500":
          description: Internal server error
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CustomerDto"
    put:
      tags:
      - customer-controller
      summary: Updates an existing customer
      description: Updates the data of an existing customer in the system
      operationId: updateCustomer
      requestBody:
        description: The updated data of the customer
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerDto"
            examples:
              customer_updated:
                description: customer_updated
                value:
                  id: 1
                  firstName: string
                  lastName: string
                  birthDate: 2025-04-05
                  email: string
              customer_updated_notFound:
                description: customer_updated_notFound
                value:
                  id: 999999999
                  firstName: string
                  lastName: string
                  birthDate: 2025-04-05
                  email: string
              customer_updated_invalid:
                description: customer_updated_invalid
                value:
                  id: 1
                  firstName: ""
                  lastName: string
                  birthDate: 2025-04-05
                  email: string
        required: true
      responses:
        "200":
          description: Customer successfully updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDto"
              examples:
                customer_updated:
                  description: customer_updated
                  value: |
                    {
                      "id": {{ request.body/id }},
                      "firstName": "{{ request.body/firstName }}",
                      "lastName": "{{ request.body/lastName }}",
                      "birthDate": "{{ request.body/birthDate }}",
                      "email": "{{ request.body/email }}"
                    }
        "400":
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetail"
              examples:
                customer_updated_invalid:
                  description: customer_updated_invalid
        "404":
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetail"
              examples:
                customer_updated_notFound:
                  description: customer_updated_notFound
    post:
      tags:
      - customer-controller
      summary: Creates a new customer
      description: Creates a new customer in the system
      operationId: createCustomer
      requestBody:
        description: The data of the customer to be created
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCustomerDto"
            examples:
              customer_created:
                description: customer_created
                value:
                  firstName: Max
                  lastName: Mustermann
                  birthDate: 2025-04-05
                  email: max.mustermann@web.de
              customer_created_invalid_firstname:
                description: customer_created_invalid_firstname
                value:
                  firstName: ""
                  lastName: Mustermann
                  birthDate: 2025-04-05
                  email: null
              customer_created_invalid_lastname:
                description: customer_created_invalid_lastname
                value:
                  firstName: string
                  lastName: ""
                  birthDate: 2025-04-05
                  email: null
              customer_created_invalid_birthDate:
                description: customer_created_invalid_birthDate
                value:
                  firstName: string
                  lastName: ""
                  birthDate: 2025-04-05
                  email: null
        required: true
      responses:
        "201":
          description: Customer successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDto"
              examples:
                customer_created:
                  description: customer_created
                  value:
                    id: 1
                    firstName: string
                    lastName: string
                    birthDate: 2025-04-05
                    email: string
        "400":
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                customer_created_invalid_firstname:
                  description: customer_created_invalid_firstname
                  value:
                    message: Validierungsfehler
                    errors:
                      firstName: Vorname darf nicht leer sein
                customer_created_invalid_lastname:
                  description: customer_created_invalid_lastname
                  value:
                    message: Validierungsfehler
                    errors:
                      lastName: Nachname darf nicht leer sein
                customer_created_invalid_birthDate:
                  description: customer_created_invalid_birthDate
                  value:
                    message: Validierungsfehler
                    errors:
                      birthDate: Geburtsdatum ist ungültig
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CustomerDto"
  /customers/{id}:
    get:
      tags:
      - customer-controller
      summary: Retrieves a customer
      operationId: getCustomerById
      parameters:
      - name: id
        in: path
        description: The ID of the customer
        required: true
        schema:
          type: integer
          format: int64
        examples:
          customer_not_found:
            description: customer_not_found
            value: 9999999999
          customer_found:
            description: customer_found
            value: 1
      responses:
        "200":
          description: Customer found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerDto"
              examples:
                customer_found:
                  description: customer_found
                  value:
                    id: 1
                    firstName: string
                    lastName: string
                    birthDate: 2025-04-05
                    email: string
        "404":
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetail"
              examples:
                customer_not_found:
                  description: customer_not_found
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CustomerDto"
    delete:
      tags:
      - customer-controller
      summary: Deletes an existing customer
      description: Deletes an existing customer from the system
      operationId: deleteCustomer
      parameters:
      - name: id
        in: path
        description: The ID of the customer to be deleted
        required: true
        schema:
          type: integer
          format: int64
        examples:
          non_customer:
            description: non_customer
            value: 9999999999
          customer_deleted:
            description: customer_deleted
            value: 1
      responses:
        "204":
          description: Customer successfully deleted
          content:
            application/json:
              examples:
                customer_deleted:
                  description: customer_deleted
                non_customer:
                  description: non_customer
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    CustomerDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
          minLength: 1
        lastName:
          type: string
          minLength: 1
        birthDate:
          type: string
          format: date
        email:
          type: string
      required:
      - birthDate
      - id
    ProblemDetail:
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
          format: int32
        detail:
          type: string
        instance:
          type: string
          format: uri
        properties:
          type: object
          additionalProperties:
            type: object
    CreateCustomerDto:
      type: object
      properties:
        firstName:
          type: string
          minLength: 1
        lastName:
          type: string
          minLength: 1
        birthDate:
          type: string
          format: date
        email:
          type: string
      required:
      - birthDate
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        errors:
          type: object
          additionalProperties:
            type: string
