-- liquibase formatted sql

-- changeset robert:1743856031017-1
CREATE TABLE customer
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    birth_date date                                    NOT NULL,
    email      VARCHAR(255),
    PRIMARY KEY (id)
);

-- changeset robert:1743856031017-2
INSERT INTO customer (first_name, last_name, birth_date, email)
VALUES ('John', 'Doe', '1990-01-15', 'john.doe@example.com');

